ENV:
  sim_path: 'simulator/goseek-v0.1.2.x86_64'
  ground_truth_mode: false
  metadata_port: 9007
  image_port: 9008

EPISODE:
  scenes: [3, 5]
  n_targets: [30, 30]
  episode_length: [200, 200]
  random_seeds: [10, 5]
